[package]
name = "rs-japanese-ocr"
version = "0.1.0"
edition = "2024"
description = "Japanese OCR WASM compatible library for japanese text recognition"
license = "AGPL-3.0"
repository = "https://github.com/yurvon-screamo/japanese-ocr"
authors = ["yurvon_screamo"]
keywords = ["ocr", "manga", "japanese", "text-recognition", "wasm"]
categories = ["computer-vision", "text-processing"]

[dependencies]
prost.workspace = true
thiserror.workspace = true
image.workspace = true
candle-core.workspace = true
candle-onnx.workspace = true
tokenizers.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
reqwest = { version = "0.12", features = ["rustls-tls"], default-features = false }
dirs = "6"
tokio = { version = "1", features = ["rt", "fs", "io-util", "macros", "rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
    "Cache",
    "CacheStorage",
    "Storage",
    "Headers",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = []
static-model = []
